version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    environment:
      - GRAFANA_PORT=${GRAFANA_PORT:-3000}
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}      
      - GF_USERS_ALLOW_SIGN_UP=false        
    volumes:
      - grafana-data:/var/lib/grafana
      - type: bind
        source: ./grafana/loki-datasource.yaml
        target: /etc/grafana/provisioning/datasources/loki-datasource.yaml
      - type: bind
        source: ./grafana/loki-dashboard.json
        target: /etc/grafana/provisioning/dashboards/loki-dashboard.json  
    ports:
      - '${GRAFANA_PORT}:3000'
    networks:
      - urbalurba-network

  loki:
    image: grafana/loki:latest
    ports:
      - '3100:3100'      
    volumes:
      - loki-data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - urbalurba-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - HTTP_PASSWORD=${REDIS_COMMANDER_PASSWORD:-admin}
      - HTTP_USER=${REDIS_COMMANDER_USER:-admin}
      - REDIS_COMMANDER_PORT=${REDIS_COMMANDER_PORT:-8082}
    ports:
      - '${REDIS_COMMANDER_PORT}:8081'      
    networks:
      - urbalurba-network          

volumes:
  grafana-data:
  loki-data:

networks:
  urbalurba-network:
    external: true
