name: Docker Build and Push

on:
  push:
    branches: [ main ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2 
      with:
        registry: ghcr.io
        username: terchris
        password: ${{ secrets.CR_PAT }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
#        platforms: linux/amd64,linux/arm64
        platforms: linux/amd64
        push: true
        tags: ghcr.io/terchris/urbalurba-manage:latest

